-- Seed community_scores with initial baseline data
-- Run once in Supabase SQL editor

INSERT INTO community_scores (list_id, item_title, total_score, participant_count)
VALUES
  ('community-movies', 'The Godfather', 196, 28),
  ('community-movies', 'Schindler''s List', 187, 28),
  ('community-movies', 'The Shawshank Redemption', 177, 28),
  ('community-movies', 'Pulp Fiction', 166, 28),
  ('community-movies', '2001: A Space Odyssey', 154, 28),
  ('community-movies', 'Citizen Kane', 142, 28),
  ('community-movies', 'Casablanca', 128, 28),
  ('community-movies', 'Parasite', 114, 28),
  ('community-movies', 'The Dark Knight', 98, 28),
  ('community-movies', 'Spirited Away', 80, 28),
  ('community-tv', 'Breaking Bad', 196, 28),
  ('community-tv', 'The Wire', 185, 28),
  ('community-tv', 'The Sopranos', 173, 28),
  ('community-tv', 'Game of Thrones', 161, 28),
  ('community-tv', 'Succession', 147, 28),
  ('community-tv', 'Chernobyl', 133, 28),
  ('community-tv', 'Fleabag', 118, 28),
  ('community-tv', 'The Bear', 101, 28),
  ('community-tv', 'Fargo', 83, 28),
  ('community-tv', 'Arrested Development', 63, 28),
  ('community-songs', 'Bohemian Rhapsody', 196, 28),
  ('community-songs', 'Imagine', 189, 28),
  ('community-songs', 'Smells Like Teen Spirit', 182, 28),
  ('community-songs', 'What''s Going On', 174, 28),
  ('community-songs', 'Like a Rolling Stone', 165, 28),
  ('community-songs', 'God Only Knows', 156, 28),
  ('community-songs', 'Purple Rain', 146, 28),
  ('community-songs', 'Good Vibrations', 134, 28),
  ('community-songs', 'Waterloo Sunset', 122, 28),
  ('community-songs', 'I Will Always Love You', 109, 28),
  ('community-athletes', 'Michael Jordan', 196, 28),
  ('community-athletes', 'Muhammad Ali', 189, 28),
  ('community-athletes', 'Serena Williams', 182, 28),
  ('community-athletes', 'Lionel Messi', 174, 28),
  ('community-athletes', 'Usain Bolt', 165, 28),
  ('community-athletes', 'Michael Phelps', 155, 28),
  ('community-athletes', 'Simone Biles', 145, 28),
  ('community-athletes', 'Tiger Woods', 134, 28),
  ('community-athletes', 'LeBron James', 122, 28),
  ('community-athletes', 'Roger Federer', 108, 28),
  ('community-books', 'To Kill a Mockingbird', 196, 28),
  ('community-books', '1984', 181, 28),
  ('community-books', 'The Great Gatsby', 165, 28),
  ('community-books', 'One Hundred Years of Solitude', 148, 28),
  ('community-books', 'Pride and Prejudice', 131, 28),
  ('community-books', 'Crime and Punishment', 112, 28),
  ('community-books', 'Beloved', 92, 28),
  ('community-books', 'Don Quixote', 71, 28),
  ('community-books', 'Middlemarch', 48, 28),
  ('community-books', 'The Brothers Karamazov', 33, 28),
  ('community-food', 'Pizza', 196, 28),
  ('community-food', 'Sushi', 185, 28),
  ('community-food', 'Tacos', 174, 28),
  ('community-food', 'Ramen', 162, 28),
  ('community-food', 'Pasta', 148, 28),
  ('community-food', 'Fried Chicken', 134, 28),
  ('community-food', 'Cheeseburger', 119, 28),
  ('community-food', 'Peking Duck', 103, 28),
  ('community-food', 'Croissant', 85, 28),
  ('community-food', 'Chocolate Cake', 66, 28),
  ('community-gaming', 'The Legend of Zelda: Ocarina of Time', 196, 28),
  ('community-gaming', 'The Last of Us', 183, 28),
  ('community-gaming', 'Red Dead Redemption 2', 169, 28),
  ('community-gaming', 'Super Mario 64', 154, 28),
  ('community-gaming', 'Minecraft', 138, 28),
  ('community-gaming', 'The Witcher 3', 121, 28),
  ('community-gaming', 'Tetris', 103, 28),
  ('community-gaming', 'Dark Souls', 83, 28),
  ('community-gaming', 'Half-Life 2', 62, 28),
  ('community-gaming', 'GTA V', 40, 28),
  ('community-people', 'Isaac Newton', 196, 28),
  ('community-people', 'Albert Einstein', 184, 28),
  ('community-people', 'Leonardo da Vinci', 172, 28),
  ('community-people', 'Nelson Mandela', 158, 28),
  ('community-people', 'Marie Curie', 144, 28),
  ('community-people', 'Abraham Lincoln', 128, 28),
  ('community-people', 'Nikola Tesla', 112, 28),
  ('community-people', 'Martin Luther King Jr.', 94, 28),
  ('community-people', 'Steve Jobs', 74, 28),
  ('community-people', 'Malala Yousafzai', 53, 28),
  ('community-fashion', 'Audrey Hepburn', 154, 22),
  ('community-fashion', 'David Bowie', 140, 22),
  ('community-fashion', 'Coco Chanel', 126, 22),
  ('community-fashion', 'Prince', 111, 22),
  ('community-fashion', 'Rihanna', 95, 22),
  ('community-fashion', 'James Dean', 79, 22),
  ('community-fashion', 'Marilyn Monroe', 62, 22),
  ('community-fashion', 'Kate Moss', 44, 22),
  ('community-fashion', 'Pharrell Williams', 35, 22),
  ('community-fashion', 'Zendaya', 35, 22),
  ('community-health', 'Daily Exercise', 126, 18),
  ('community-health', 'Consistent Sleep Schedule', 113, 18),
  ('community-health', 'Drinking Enough Water', 99, 18),
  ('community-health', 'Meditation', 85, 18),
  ('community-health', 'Eating Whole Foods', 70, 18),
  ('community-health', 'Limiting Screen Time', 54, 18),
  ('community-health', 'Walking 10,000 Steps', 39, 18),
  ('community-health', 'Journaling', 36, 18),
  ('community-health', 'Cold Showers', 35, 18),
  ('community-health', 'Cutting Out Sugar', 34, 18),
  ('community-tech', 'The Internet', 196, 28),
  ('community-tech', 'The Smartphone', 182, 28),
  ('community-tech', 'The Printing Press', 167, 28),
  ('community-tech', 'Electricity', 151, 28),
  ('community-tech', 'The Steam Engine', 134, 28),
  ('community-tech', 'Artificial Intelligence', 116, 28),
  ('community-tech', 'The Automobile', 97, 28),
  ('community-tech', 'Penicillin', 76, 28),
  ('community-tech', 'The Airplane', 55, 28),
  ('community-tech', 'The Vaccine', 32, 28),
  ('community-arts', 'The Mona Lisa', 98, 14),
  ('community-arts', 'The Starry Night', 87, 14),
  ('community-arts', 'The Sistine Chapel Ceiling', 76, 14),
  ('community-arts', 'Guernica — Picasso', 64, 14),
  ('community-arts', 'The Birth of Venus — Botticelli', 52, 14),
  ('community-arts', 'The Scream — Edvard Munch', 40, 14),
  ('community-arts', 'Girl with a Pearl Earring — Vermeer', 36, 14),
  ('community-arts', 'The Persistence of Memory — Dalí', 36, 14),
  ('community-arts', 'Water Lilies — Monet', 35, 14),
  ('community-arts', 'The Thinker — Rodin', 35, 14),
  ('community-misc', 'See a total solar eclipse', 196, 28),
  ('community-misc', 'Watch a live World Cup or Olympics', 184, 28),
  ('community-misc', 'Sleep under the stars in the wild', 171, 28),
  ('community-misc', 'Learn a second language', 157, 28),
  ('community-misc', 'Live abroad for at least a year', 143, 28),
  ('community-misc', 'Do something that truly scares you', 127, 28),
  ('community-misc', 'Write something meant to last', 109, 28),
  ('community-misc', 'Cook a meal from scratch for others', 91, 28),
  ('community-misc', 'Disconnect from tech for a week', 71, 28),
  ('community-misc', 'Watch the sunrise from a mountaintop', 49, 28),
  ('community-golf-greatest', 'Jack Nicklaus', 133, 19),
  ('community-golf-greatest', 'Tiger Woods', 120, 19),
  ('community-golf-greatest', 'Ben Hogan', 106, 19),
  ('community-golf-greatest', 'Arnold Palmer', 92, 19),
  ('community-golf-greatest', 'Sam Snead', 77, 19),
  ('community-golf-greatest', 'Gary Player', 61, 19),
  ('community-golf-greatest', 'Bobby Jones', 45, 19),
  ('community-golf-greatest', 'Tom Watson', 36, 19),
  ('community-golf-greatest', 'Phil Mickelson', 35, 19),
  ('community-golf-greatest', 'Rory McIlroy', 34, 19),
  ('community-tennis-greatest', 'Novak Djokovic', 196, 28),
  ('community-tennis-greatest', 'Roger Federer', 183, 28),
  ('community-tennis-greatest', 'Rafael Nadal', 169, 28),
  ('community-tennis-greatest', 'Serena Williams', 154, 28),
  ('community-tennis-greatest', 'Steffi Graf', 138, 28),
  ('community-tennis-greatest', 'Pete Sampras', 121, 28),
  ('community-tennis-greatest', 'Rod Laver', 103, 28),
  ('community-tennis-greatest', 'Martina Navratilova', 83, 28),
  ('community-tennis-greatest', 'Björn Borg', 61, 28),
  ('community-tennis-greatest', 'Margaret Court', 39, 28),
  ('community-baseball-teams', '1927 New York Yankees', 105, 15),
  ('community-baseball-teams', '1998 New York Yankees', 94, 15),
  ('community-baseball-teams', '1976 Cincinnati Reds (Big Red Machine)', 82, 15),
  ('community-baseball-teams', '1906 Chicago Cubs (116-36)', 69, 15),
  ('community-baseball-teams', '2001 Seattle Mariners (116-46)', 56, 15),
  ('community-baseball-teams', '1961 New York Yankees', 43, 15),
  ('community-baseball-teams', '1969 New York Mets (Miracle Mets)', 36, 15),
  ('community-baseball-teams', '1986 New York Mets', 36, 15),
  ('community-baseball-teams', '1995 Atlanta Braves', 35, 15),
  ('community-baseball-teams', '1975 Cincinnati Reds', 35, 15),
  ('community-baseball-greatest', 'Babe Ruth', 182, 26),
  ('community-baseball-greatest', 'Willie Mays', 168, 26),
  ('community-baseball-greatest', 'Hank Aaron', 152, 26),
  ('community-baseball-greatest', 'Ted Williams', 136, 26),
  ('community-baseball-greatest', 'Lou Gehrig', 119, 26),
  ('community-baseball-greatest', 'Barry Bonds', 101, 26),
  ('community-baseball-greatest', 'Mickey Mantle', 82, 26),
  ('community-baseball-greatest', 'Ty Cobb', 61, 26),
  ('community-baseball-greatest', 'Walter Johnson', 38, 26),
  ('community-baseball-greatest', 'Mike Trout', 34, 26),
  ('community-football-greatest', 'Jerry Rice', 196, 28),
  ('community-football-greatest', 'Tom Brady', 188, 28),
  ('community-football-greatest', 'Jim Brown', 179, 28),
  ('community-football-greatest', 'Lawrence Taylor', 170, 28),
  ('community-football-greatest', 'Joe Montana', 160, 28),
  ('community-football-greatest', 'Barry Sanders', 149, 28),
  ('community-football-greatest', 'Reggie White', 137, 28),
  ('community-football-greatest', 'Walter Payton', 124, 28),
  ('community-football-greatest', 'Peyton Manning', 110, 28),
  ('community-football-greatest', 'Johnny Unitas', 94, 28),
  ('community-football-stadiums', 'Lambeau Field, Green Bay', 147, 21),
  ('community-football-stadiums', 'Arrowhead Stadium, Kansas City', 133, 21),
  ('community-football-stadiums', 'Soldier Field, Chicago', 119, 21),
  ('community-football-stadiums', 'Allegiant Stadium, Las Vegas', 104, 21),
  ('community-football-stadiums', 'SoFi Stadium, Inglewood', 87, 21),
  ('community-football-stadiums', 'AT&T Stadium, Arlington', 71, 21),
  ('community-football-stadiums', 'MetLife Stadium, East Rutherford', 41, 21),
  ('community-football-stadiums', 'Hard Rock Stadium, Miami', 36, 21),
  ('community-football-stadiums', 'Gillette Stadium, Foxborough', 35, 21),
  ('community-soccer-greatest', 'Pelé', 196, 28),
  ('community-soccer-greatest', 'Lionel Messi', 189, 28),
  ('community-soccer-greatest', 'Diego Maradona', 181, 28),
  ('community-soccer-greatest', 'Ronaldo (R9)', 172, 28),
  ('community-soccer-greatest', 'Cristiano Ronaldo', 163, 28),
  ('community-soccer-greatest', 'Johan Cruyff', 153, 28),
  ('community-soccer-greatest', 'Zinedine Zidane', 142, 28),
  ('community-soccer-greatest', 'Ronaldinho', 130, 28),
  ('community-soccer-greatest', 'Franz Beckenbauer', 117, 28),
  ('community-soccer-greatest', 'Michel Platini', 102, 28),
  ('community-soccer-wcteams', 'Brazil 1970 — Pelé, Jairzinho, Rivelino', 119, 17),
  ('community-soccer-wcteams', 'Netherlands 1974 — Cruyff & Total Football', 106, 17),
  ('community-soccer-wcteams', 'Brazil 1958 — Pelé & Garrincha', 93, 17),
  ('community-soccer-wcteams', 'France 1998 — Zidane, Henry, Desailly', 79, 17),
  ('community-soccer-wcteams', 'Argentina 1986 — Maradona''s tournament', 65, 17),
  ('community-soccer-wcteams', 'Germany 1974 — Beckenbauer & Müller', 49, 17),
  ('community-soccer-wcteams', 'Italy 1982 — Paolo Rossi & Zoff', 38, 17),
  ('community-soccer-wcteams', 'Hungary 1954 — Puskás & the Golden Team', 36, 17),
  ('community-soccer-wcteams', 'Brazil 1982 — Zico, Sócrates & Falcão', 35, 17),
  ('community-soccer-wcteams', 'Argentina 2022 — Messi''s World Cup', 35, 17),
  ('community-hockey-greatest', 'Wayne Gretzky', 140, 20),
  ('community-hockey-greatest', 'Mario Lemieux', 126, 20),
  ('community-hockey-greatest', 'Gordie Howe', 112, 20),
  ('community-hockey-greatest', 'Bobby Orr', 97, 20),
  ('community-hockey-greatest', 'Maurice Richard', 81, 20),
  ('community-hockey-greatest', 'Jean Béliveau', 65, 20),
  ('community-hockey-greatest', 'Phil Esposito', 48, 20),
  ('community-hockey-greatest', 'Mark Messier', 37, 20),
  ('community-hockey-greatest', 'Patrick Roy', 36, 20),
  ('community-hockey-greatest', 'Guy Lafleur', 35, 20),
  ('community-hockey-teams', '1976-77 Montreal Canadiens (60-8-12)', 77, 11),
  ('community-hockey-teams', '1995-96 Detroit Red Wings (62-13-7)', 67, 11),
  ('community-hockey-teams', '1983-84 Edmonton Oilers (57-18-5)', 57, 11),
  ('community-hockey-teams', '1971-72 Boston Bruins (54-13-11)', 46, 11),
  ('community-hockey-teams', '1977-78 Montreal Canadiens', 37, 11),
  ('community-hockey-teams', '1984-85 Edmonton Oilers', 37, 11),
  ('community-hockey-teams', '1991-92 Pittsburgh Penguins', 37, 11),
  ('community-hockey-teams', '2022-23 Boston Bruins (65-12-5)', 37, 11),
  ('community-hockey-teams', '1986-87 Edmonton Oilers', 37, 11),
  ('community-hockey-teams', '2018-19 Tampa Bay Lightning', 37, 11),
  ('community-basketball-teams', '1995-96 Chicago Bulls (72-10)', 112, 16),
  ('community-basketball-teams', '2015-16 Golden State Warriors (73-9)', 100, 16),
  ('community-basketball-teams', '1971-72 Los Angeles Lakers (69-13)', 87, 16),
  ('community-basketball-teams', '1966-67 Philadelphia 76ers (68-13)', 74, 16),
  ('community-basketball-teams', '1985-86 Boston Celtics (67-15)', 60, 16),
  ('community-basketball-teams', '2016-17 Golden State Warriors (67-15)', 47, 16),
  ('community-basketball-teams', '1982-83 Philadelphia 76ers (65-17)', 37, 16),
  ('community-basketball-teams', '2012-13 Miami Heat (66-16)', 36, 16),
  ('community-basketball-teams', '1986-87 Los Angeles Lakers (65-17)', 35, 16),
  ('community-basketball-teams', '1996-97 Chicago Bulls (69-13)', 35, 16),
  ('community-basketball-goat', 'Michael Jordan', 196, 28),
  ('community-basketball-goat', 'LeBron James', 189, 28),
  ('community-basketball-goat', 'Kareem Abdul-Jabbar', 180, 28),
  ('community-basketball-goat', 'Magic Johnson', 172, 28),
  ('community-basketball-goat', 'Larry Bird', 162, 28),
  ('community-basketball-goat', 'Bill Russell', 152, 28),
  ('community-basketball-goat', 'Wilt Chamberlain', 141, 28),
  ('community-basketball-goat', 'Tim Duncan', 129, 28),
  ('community-basketball-goat', 'Kobe Bryant', 116, 28),
  ('community-basketball-goat', 'Shaquille O''Neal', 101, 28),
  ('community-sandwich-shops', 'Katz''s Delicatessen', 126, 18),
  ('community-sandwich-shops', 'Turkey and the Wolf', 118, 18),
  ('community-sandwich-shops', 'Primanti Bros', 110, 18),
  ('community-sandwich-shops', 'Paesano''s', 103, 18),
  ('community-sandwich-shops', 'Cochon Butcher', 95, 18),
  ('community-sandwich-shops', 'Ike''s Love & Sandwiches', 88, 18),
  ('community-sandwich-shops', 'Mr. Beef on Orleans', 79, 18),
  ('community-sandwich-shops', 'Publican Quality Meats', 71, 18),
  ('community-sandwich-shops', 'Brennan & Carr', 62, 18),
  ('community-sandwich-shops', 'Mendocino Farms', 53, 18),
  ('community-sandwich-chains', 'Jersey Mike''s Subs', 196, 28),
  ('community-sandwich-chains', 'Firehouse Subs', 184, 28),
  ('community-sandwich-chains', 'Jimmy John''s', 171, 28),
  ('community-sandwich-chains', 'McAlister''s Deli', 158, 28),
  ('community-sandwich-chains', 'Jason''s Deli', 145, 28),
  ('community-sandwich-chains', 'Potbelly Sandwich Works', 131, 28),
  ('community-sandwich-chains', 'Which Wich', 117, 28),
  ('community-sandwich-chains', 'Capriotti''s Sandwich Shop', 102, 28),
  ('community-sandwich-chains', 'Subway', 86, 28),
  ('community-sandwich-chains', 'Quiznos', 69, 28),
  ('community-bakeries', 'Tartine Bakery', 154, 22),
  ('community-bakeries', 'Levain Bakery', 145, 22),
  ('community-bakeries', 'Ken''s Artisan Bakery', 135, 22),
  ('community-bakeries', 'Bien Cuit', 125, 22),
  ('community-bakeries', 'Sullivan Street Bakery', 116, 22),
  ('community-bakeries', 'Zingerman''s Bakehouse', 105, 22),
  ('community-bakeries', 'Republique', 94, 22),
  ('community-bakeries', 'Balthazar Bakery', 83, 22),
  ('community-bakeries', 'Seven Stars Bakery', 71, 22),
  ('community-bakeries', 'La Farm Bakery', 58, 22),
  ('community-pastry-shops', 'Dominique Ansel Bakery', 133, 19),
  ('community-pastry-shops', 'Milk Bar', 125, 19),
  ('community-pastry-shops', 'Bouchon Bakery', 116, 19),
  ('community-pastry-shops', 'Flour Bakery + Cafe', 106, 19),
  ('community-pastry-shops', 'Porto''s Bakery', 97, 19),
  ('community-pastry-shops', 'Bottega Louie', 88, 19),
  ('community-pastry-shops', 'Craftsman and Wolves', 79, 19),
  ('community-pastry-shops', 'Bang Bang Pie & Biscuits', 68, 19),
  ('community-pastry-shops', 'Pâtisserie Chanson', 58, 19),
  ('community-pastry-shops', 'Mah-Ze-Dahr Bakery', 46, 19),
  ('community-diners', 'Lou Mitchell''s', 189, 27),
  ('community-diners', 'Mickey''s Diner', 177, 27),
  ('community-diners', 'Mel''s Drive-In', 165, 27),
  ('community-diners', 'Tick Tock Diner', 152, 27),
  ('community-diners', 'The Original Pancake House', 139, 27),
  ('community-diners', 'Square Diner', 124, 27),
  ('community-diners', 'Veselka', 109, 27),
  ('community-diners', 'The Blue Benn', 93, 27),
  ('community-diners', 'Slim''s Last Chance', 77, 27),
  ('community-diners', 'Nick''s Diner', 60, 27),
  ('community-fast-food', 'In-N-Out Burger', 196, 28),
  ('community-fast-food', 'Chick-fil-A', 187, 28),
  ('community-fast-food', 'Whataburger', 176, 28),
  ('community-fast-food', 'Five Guys', 165, 28),
  ('community-fast-food', 'Raising Cane''s', 153, 28),
  ('community-fast-food', 'Culver''s', 141, 28),
  ('community-fast-food', 'Popeyes', 127, 28),
  ('community-fast-food', 'Shake Shack', 114, 28),
  ('community-fast-food', 'Sonic Drive-In', 99, 28),
  ('community-fast-food', 'McDonald''s', 82, 28),
  ('community-fast-casual', 'Chipotle Mexican Grill', 196, 28),
  ('community-fast-casual', 'Shake Shack', 185, 28),
  ('community-fast-casual', 'First Watch', 173, 28),
  ('community-fast-casual', 'Panera Bread', 161, 28),
  ('community-fast-casual', 'Noodles & Company', 148, 28),
  ('community-fast-casual', 'Cafe Rio', 135, 28),
  ('community-fast-casual', 'Blaze Pizza', 120, 28),
  ('community-fast-casual', 'The Habit Burger Grill', 105, 28),
  ('community-fast-casual', 'Mod Pizza', 90, 28),
  ('community-fast-casual', 'Panda Express', 73, 28),
  ('community-bbq', 'Franklin Barbecue', 196, 28),
  ('community-bbq', 'Goldee''s Barbecue', 185, 28),
  ('community-bbq', 'Snow''s BBQ', 174, 28),
  ('community-bbq', 'Pecan Lodge', 162, 28),
  ('community-bbq', 'Joe''s Kansas City BBQ', 149, 28),
  ('community-bbq', '17th Street BBQ', 137, 28),
  ('community-bbq', 'Hometown Bar-B-Que', 123, 28),
  ('community-bbq', 'Scott''s Bar-B-Que', 109, 28),
  ('community-bbq', 'Central BBQ', 93, 28),
  ('community-bbq', 'Dreamland Bar-B-Que', 77, 28),
  ('community-salad-chains', 'Sweetgreen', 196, 28),
  ('community-salad-chains', 'Cava', 184, 28),
  ('community-salad-chains', 'Dig', 172, 28),
  ('community-salad-chains', 'Just Salad', 159, 28),
  ('community-salad-chains', 'Mixt', 145, 28),
  ('community-salad-chains', 'Chopt Creative Salad Co.', 130, 28),
  ('community-salad-chains', 'Tender Greens', 115, 28),
  ('community-salad-chains', 'Lemonade Restaurant', 99, 28),
  ('community-salad-chains', 'Nékter Juice Bar', 82, 28),
  ('community-salad-chains', 'Salata', 64, 28)
ON CONFLICT (list_id, item_title)
DO UPDATE SET
  total_score = EXCLUDED.total_score,
  participant_count = EXCLUDED.participant_count;